name: Get Branch From Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  get_branch:
    runs-on: ubuntu-latest
    steps:
      - id: get_branch
        name: Get Branch
        run: |
          echo "$(echo $GITHUB_REF | sed 's/refs\/tags\///')"
          echo "$(git branch --contains tags/$GITHUB_REF)"
