name: Get Branch From Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  get_branch:
    runs-on: ubuntu-latest
    steps:
      - id: get_branch
        name: Get Branch
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 2
          github-token: ${{ github.token }}
          script: |
            console.log(github)
