name: Provision PosgreSQL Server and Install the Extension

on:
  push:
    branches:
      - master

jobs:
  provision-postgresql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres

    steps:
      - name: Verify PostgreSQL Running
        shell: bash
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d postgres -c "SELECT version();"

      - name: Test Exec to PostgreSQL Container
        shell: bash
        run: |
          /usr/bin/docker exec postgres echo "Hello World"

      - name: Install Partman Extension
        shell: bash
        run: |
          /usr/bin/docker exec postgres \
          apt update && apt install -y make gcc wget postgresql-server-dev-14 && \
          wget https://github.com/pgpartman/pg_partman/archive/refs/tags/v4.4.0.tar.gz && \
          tar -xzvf v4.4.0.tar.gz && \
          cd pg_partman-4.4.0 && \
          make install