name: Provision PosgreSQL Server and Install the Extension

on:
  push:
    branches:
      - master

jobs:
  provision-postgresql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Verify PostgreSQL Running
        shell: bash
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d postgres -c "SELECT version();"